# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20160410_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
