# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0013_auto_20160417_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='submission.Submission'),
        ),
    ]
