# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0016_comment_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('Science and Engineering', 'Science and Engineering'), ('Health Sciences', 'Health Sciences'), ('Humanities', 'Humanities')], max_length=30),
        ),
    ]
