# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0020_comvoting_subvoting'),
    ]

    operations = [
        migrations.AddField(
            model_name='comvoting',
            name='downVote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comvoting',
            name='submission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comvotes', to='submission.Submission'),
        ),
        migrations.AddField(
            model_name='comvoting',
            name='upVote',
            field=models.BooleanField(default=False),
        ),
    ]
