# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0021_auto_20160424_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Engineering', 'Engineering'), ('Health Sciences', 'Health Sciences'), ('Arts', 'Arts'), ('Humanities', 'Humanities')], max_length=30),
        ),
    ]
