# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0022_auto_20160508_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comvoting',
            old_name='downVote',
            new_name='downvote',
        ),
        migrations.RenameField(
            model_name='comvoting',
            old_name='upVote',
            new_name='upvote',
        ),
    ]
