# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160319_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=0, max_length=40),
        ),
    ]
