# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=0, max_length=100),
        ),
    ]
