# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160405_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default=models.EmailField(max_length=255, unique=True, verbose_name='email address'), max_length=100),
        ),
    ]
