# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160405_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
