# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160422_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
