# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160507_1931'),
        ('accounts', '0010_auto_20160508_1057'),
    ]

    operations = [
    ]
